version: '3.7'
services:
  postgres:
    image: postgres:11.3-alpine
    container_name: portal_deployment_postgres
    restart: always
    ports:
      - 15432:5432
    volumes:
      - ./docker/data/postgres:/var/lib/postgres/data
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    volumes:
      - .:/home/dst/portal_deployment/application
      - ./game_files:/home/dst/portal_deployment/game_files
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    depends_on:
      - postgres
    command: sleep infinity